apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sonarApp.name" . }}qube-data
spec:
  storageClassName: {{ .Values.sonarApp.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarApp.storage.storageRequestSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sonarApp.name" . }}qube-extensions
spec:
  storageClassName: {{ .Values.sonarApp.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarApp.storage.storageRequestSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonarApp.name" . }}-app
  labels:
    app: {{ template "sonarApp.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sonarApp.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "sonarApp.name" . }}
    spec:
      containers:
        - name: {{ template "sonarApp.name" . }}-appserver
          image: {{ .Values.sonarApp.image.repository }}
          ports:
            - name: sonarqube
              containerPort: {{ .Values.sonarApp.service.targetPort }}
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: {{ .Values.sonarApp.sonarUsername }}
            - name: SONARQUBE_JDBC_PASSWORD
              value: {{ .Values.sonarApp.sonarPassword }}
            - name: SONARQUBE_JDBC_URL
              value: jdbc:mysql://{{ .Values.mysqlApp.appname }}-service:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
          volumeMounts:
            - name: {{ template "sonarApp.name" . }}qube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: {{ template "sonarApp.name" . }}qube-data
              mountPath: /opt/sonarqube/data
      volumes:
        - name: {{ template "sonarApp.name" . }}qube-extensions
          persistentVolumeClaim:
            claimName: {{ template "sonarApp.name" . }}qube-extensions
        - name: {{ template "sonarApp.name" . }}qube-data
          persistentVolumeClaim:
            claimName: {{ template "sonarApp.name" . }}qube-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
