apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sonarApp.name" . }}-app
  labels:
    app: {{ template "sonarApp.name" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar-deployment
    spec:
      containers:
        - name: {{ template "sonarApp.name" . }}-appserver
          image: {{ .Values.sonarApp.image.repository }}
          ports:
            - name: sonarqube
              containerPort: {{ .Values.sonarApp.service.targetPort }}
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: sonar
            - name: SONARQUBE_JDBC_PASSWORD
              value: sonar
            - name: SONARQUBE_JDBC_URL
              value: jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
          volumeMounts:
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonarqube-extensions
          nfs:
            server: ""
            path: "/sonarqube/extensions"
            readOnly: false
        - name: sonarqube-data
          nfs:
            server: ""
            path: "/sonarqube/data"
            readOnly: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
