apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sonarApp.name" . }}qube-data
spec:
  storageClassName: {{ .Values.sonarApp.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarApp.storage.storageRequestSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sonarApp.name" . }}qube-extensions
spec:
  storageClassName: {{ .Values.sonarApp.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarApp.storage.storageRequestSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sonarApp.name" . }}-app
  labels:
    app: {{ template "sonarApp.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sonarApp.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "sonarApp.name" . }}
    spec:
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
          name: set-max-map-count
          image: busybox
          securityContext:
            privileged: true
      containers:
        - name: {{ template "sonarApp.name" . }}-appserver
          image: {{- if .Values.postreSQLApp.enabled }} {{ .Values.sonarApp.image.repository }} {{- else }} {{ .Values.sonarApp.image.repositoryMysql }} {{- end }}
          securityContext:
            privileged: true
          ports:
            - name: sonarqube
              containerPort: {{ .Values.sonarApp.service.targetPort }}
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: {{ .Values.sonarApp.sonarUsername }}
            - name: SONARQUBE_JDBC_PASSWORD
              value: {{ .Values.sonarApp.sonarPassword }}
              {{- if .Values.postreSQLApp.enabled }}
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://{{ .Values.postreSQLApp.appname }}-service:{{ .Values.postreSQLApp.service.port }}/{{ .Values.postreSQLApp.sonarDB }}
              {{- else }}
            - name: SONARQUBE_JDBC_URL
              value: jdbc:mysql://{{ .Values.mysqlApp.appname }}-service:3306/{{ .Values.postreSQLApp.sonarDB }}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&verifyServerCertificate=false&useSSL=true
              {{- end }}
          volumeMounts:
            - name: {{ template "sonarApp.name" . }}qube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: {{ template "sonarApp.name" . }}qube-data
              mountPath: /opt/sonarqube/data
      volumes:
        - name: {{ template "sonarApp.name" . }}qube-extensions
          persistentVolumeClaim:
            claimName: {{ template "sonarApp.name" . }}qube-extensions
        - name: {{ template "sonarApp.name" . }}qube-data
          persistentVolumeClaim:
            claimName: {{ template "sonarApp.name" . }}qube-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
