apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlApp.appname }}-data
spec:
  storageClassName: {{ .Values.mysqlApp.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlApp.storage.storageRequestSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysqlApp.appname }}-app
  labels:
    app: {{ .Values.mysqlApp.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysqlApp.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlApp.appname }}
    spec:
      containers:
        - name: {{ .Values.mysqlApp.appname }}-appserver
          image: {{ .Values.mysqlApp.image.repository }}
          ports:
            - containerPort: {{ .Values.mysqlApp.service.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysqlApp.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlApp.sonarDB }}
            - name: MYSQL_USER
              value: {{ .Values.mysqlApp.dbUser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlApp.dbPassword }}
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - name: {{ .Values.mysqlApp.appname }}-data
              mountPath: /var/lib/mysql
      volumes:
        - name: {{ .Values.mysqlApp.appname }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.mysqlApp.appname }}-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
