apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlApp.appname }}-service
  labels:
    name: {{ .Values.mysqlApp.appname }}-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.mysqlApp.service.port }}
  selector:
    app: {{ .Values.mysqlApp.appname }}
