#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ .Values.postreSQLApp.appname }}-service
#  labels:
#    name: {{ .Values.postreSQLApp.appname }}-service
#spec:
#  ports:
#    - protocol: TCP
#      port: {{ .Values.postreSQLApp.service.port }}
#  selector:
#    app: {{ .Values.postreSQLApp.appname }}
