apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarApp.name" . }}-service
  labels:
    name: {{ template "sonarApp.name" . }}-service
spec:
  type: {{ .Values.sonarApp.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.sonarApp.service.port }}
      targetPort: {{ .Values.sonarApp.service.targetPort }}
  selector:
    app: {{ template "sonarApp.name" . }}
