# Default values for strapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
sonarApp:
  appname: sonar
  sonarUsername: sonar
  sonarPassword: sonar
  storage:
    className: standard
    storageRequestSize: 10Gi
  image:
    repository: sonarqube:8.5.1-community
    repositoryMysql: sonarqube:6.5
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
    targetPort: 9000

mysqlApp:
  enabled: true
  appname: sonar-mysql
  dbUser: sonar
  rootPassword: password
  dbPassword: sonar
  sonarDB: sonar
  storage:
    className: standard
    storageRequestSize: 5Gi
  image:
    repository: mysql:5.7
    pullPolicy: IfNotPresent
  service:
    port: 3306

postreSQLApp:
  enabled: false
  appname: sonar-postgresql
  dbUser: sonar
  rootPassword: password
  dbPassword: sonar
  sonarDB: sonar
  storage:
    className: standard
    storageRequestSize: 5Gi
  image:
    repository: bitnami/postgresql:11.10.0-debian-10-r60
    pullPolicy: IfNotPresent
  service:
    port: 5432
